default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <your_account>           # e.g. xy12345.us-east-1
      user: <your_user>
      password: <your_password>
      role: SYSADMIN
      database: raw_db
      warehouse: compute_wh
      schema: analytics
      threads: 4
      client_session_keep_alive: False
